### ISSUE TITLE
Issue when running show partitions

### ISSUE THREAD

**Issue by BogdanCojocar** [chrispruitt/pythena#1]
Hi, 

thank you for this package, it's quite helpful. It's running ok most of the times, but I encountered and issue when trying to do a `show partitions` query:

```
df = athena_client.execute("SHOW PARTITIONS table", s3_output_url='s3://path', save_results=False)
```
throws an exception
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pythena/Athena.py", line 54, in execute
    save_results=save_results)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pythena/Athena.py", line 75, in __execute_query
    obj = self.__s3.get_object(Bucket=s3_bucket, Key=s3_key)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```

Is this something that is easy to fix? Happy to do a PR.

**Comment by chrispruitt** [comment]
I admit I wrote this package at first to offer a quick way to run easily run SELECT statements for data exploration. This would be a useful feature though for those who have partitioned tables. Athena creates a txt file in s3 instead of a csv for these queries. The execute method returns a dataframe from a csv, but i could add a little patch that would return the contents of the txt file if the csv doesn't exist. A little dirty, but its mostly a data exploration package anyway.

**Comment by chrispruitt** [comment]
ok i just pushed a patch for this, quick and dirty solution, if the query is a descriptive query it will return the contents as a string instead of a dataframe and you can simply print those out

```
results = athena_client.execute("DESCRIBE my_table")

print(results)

id                  	string              	                    
newthing            	string              	                    
name                	string              	                    
	 	 
# Partition Information	 	 
# col_name            	data_type           	comment             
	 	 
newthing            	string              	                    
name                	string              	                    
```
