### ISSUE TITLE
Database not found

### ISSUE THREAD

**Issue by calleo** [chrispruitt/pythena#6]
Hi,

I am getting an error saying a particular database doesn't exist. If I do print_databases the first few databases are printed, so I am able to connect to Glue.

We have a large number of databases in Glue, so I have a feeling get_databases in boto3 only returns the first N number for databases.

Perhaps one can use get_database to verify that it exists?

**Comment by chrispruitt** [comment]
Thanks for finding this issue. I have added support for any number of databases in the latest release `1.4.1`. Let me know if you have anymore issues and/or feel free to submit a PR for anything else you may find.
